### ISSUE TITLE
Thanks for this firmware and great documentation, works like a charm!

### ISSUE THREAD

**Issue by kynan** [remay/tmf-hudl#22]
Haven't found another place to provide feedback, so filing this issue to report that TMF 1.0 installation from SD card works like a charm on a Hudl 1. The documentation is really great, thanks! :+1:

**Comment by remay** [comment]
@kynan - thank you very much for taking the time to feedback.  I'm glad it's worked out for you.  Please spread the word and try yo keep some more devices from going to e-waste prematurely.
