### ISSUE TITLE
img file

### ISSUE THREAD

**Issue by hache23** [remay/tmf-hudl#28]
hey, i have extracted and renamed the image file on my sd card but the hudl doesnt seem to find it.  is there any thing o am missing?

**Comment by remay** [comment]
1. Download https://github.com/remay/tmf-hudl/releases/download/tmf-custom-rom-v1.0/hudl.20140424.153851.TMF-Custom-v1.0.img.zip
2. Unzip it
3. rename it 'update.img'
4. put it on your SD card (in the root directory)
5. put the SD card into the Hudl
6. Boot the Hudl into recovery
7. select the 'update rkimge from external storage' option

If  you've followed that exactly and it's not working, then take a screenshot of the Hudl (with your phone) showing the message and attach a reply here.

**Comment by hache23** [comment]
![IMG_20210126_153244(1)](https://user-images.githubusercontent.com/78033975/105867326-e2632100-5fec-11eb-8677-875ecada9a1e.jpg)
thanks for the quick reply. yep thats what ive done doesnt seem to see the image file.  i thought it was the card at first so put it in a subfloder to check found the sub folder but not the file :/

**Comment by remay** [comment]
That doesn't look like the recovery screen for a Hudl 1.  There is no option "update rkimage from external storage".  Is that a Hudl 2?   This firmware image is for Hudl 1 devices only.

**Comment by hache23** [comment]
ah yep that will be why!! is there any info on a similar process for hudl2's?

**Comment by remay** [comment]
I've not seen any custom images for the Hudl 2, but I haven't looked terribly hard as I don't have one.    I don't knwo how you ended up here, but if your stuck at the 'won't connect to internet' screen having factory reset your device, then there are reports of a method I documented for the Hudl 1 (https://rob.themayfamily.me.uk/hudl/hudl-fix) working for Hudl 2 devices - but I can't offer any support I'm afraid.
