### ISSUE TITLE
SD Card upgrade fails

### ISSUE THREAD

**Issue by remay** [remay/tmf-hudl#30]
From #23

@JavacHolt sees a failure when trying to flash from SD Card
![109796417-0b8c5800-7c10-11eb-9b6a-7a25b36e2bba](https://user-images.githubusercontent.com/83421/110111962-04e51880-7da9-11eb-8d58-d0b50504ff59.jpeg)

My initial analysis is
- there's no update to do to the parameter partition
- Update appears to succeed to the boot partition, but this is likely to be due to there being no difference in the boot partition content.
- Update to system partition fails.

If I had to guess I'd say this is another occurrence of a device with read-only EMMC chip, but user says that he can boot the device which wouldn't happen if whole chip is read only.    Perhaps it's possible for certain partition to become read-only?

**Comment by remay** [comment]
Let's confirm that we can write to the flash chip.  Please download this [update-JavacHolt01.zip](https://github.com/remay/tmf-hudl/files/6090462/update-JavacHolt01.zip) file, unzip it and put the extracted `update.img`  in the root of the SD card.  Run it following the [instructions for applying the custom ROM from the SD](https://github.com/remay/tmf-hudl/wiki/Flashing-from-an-SD-Card).  It should generate 2 new files on the SD card (`param-orig.dat` and `param-after.dat`).  Please zip those 2 files and attach to a reply to this issue.

What this should do is export the PARAM partition, supply a small update to the PARAM partition and then export it again.

**Comment by JavacHolt** [comment]
[hudl-Javac.zip](https://github.com/remay/tmf-hudl/files/6092033/hudl-Javac.zip)

hope this will provide the relevent

**Comment by remay** [comment]
That appears to confirm that we can't write to flash on your device, as the before and after data are identical.   Let me double check that I coded that test up right and that it behaves as I expect on one of my Hudl's.

However, if this is really correct then I don't understand how your device can boot at all.    Can you boot it and successfully install a new application from the play store?

**Comment by JavacHolt** [comment]
Ok, I'll try that

**Comment by JavacHolt** [comment]
Hmm, well, I can't get as far as installing and deleting through the play
store, it isn't retaining the email/ pw and when it is rebooted it forgets
the wi-fi credentials. Don't suppose it's possible to replace the storage
hardware ? 🙄

**Comment by remay** [comment]
>  Don't suppose it's possible to replace the storage hardware ? 🙄

Depends on how good your reflow soldering technique is :-). It's a chip soldered directly to the main board.
Give me until the end of the weekend to validate what we've done, but my suspicion is that your EMMC has failed to a read-only state.

**Comment by JavacHolt** [comment]
Thank you, I used to do quite a bit of soldering, even doing mods on
industrial welders, so if I can see it 🙄, I'll probably be able to do it

**Comment by remay** [comment]
I've confirmed that on a working device the `update.img` you ran should write to the parameter partition, which it doesn't on yours.  You are the second person I've come across with what appears to be a read-only EMMC chip.   Whilst it's not common I can find evidence of other devices that this sometimes happens on.

If you pull the back off  - easy with a suction cup on the back; I find sticking it near the sd card slot is usually easiest, then it's this chip:
![IMG_3629](https://user-images.githubusercontent.com/83421/110248809-d57e0980-7f6a-11eb-9764-d67a15de3870.jpg)

It's a Samsung EMMC chip.   This one is marked [KLMAG2WEMB-B031](https://www.samsung.com/semiconductor/estorage/emmc/KLMCG8WEBD-B031/) but I've seen other variants.  I suspect that like this one they are all EOL and so sourcing a new one may be hard.   You might find a new chip on Ebay, but it's likely cheaper  to look for a Hudl with a broken screen (if you're lucky you can get these as low as £3-5 plus postage) and then you just need to swap over the main board, and can avoid the risks involved with getting everything hot enough for the re-soldering.

Sorry, but I think I can't do any more with this device.

If you do want to try soldering then I have a main board on which I think the EMMC is OK (it appears to have a fault with the video driver as I can hear the Hudl start-up jingle but see no video) that I'd be happy to let you have for the cost of the postage - it's currently in my e-waste pile.  But you'd need to un-solder from this main board and move it to yours.

**Comment by JavacHolt** [comment]
Again, thanks Robert, I'll have a look and see if I can find one, but
either way I'll get back to you.

J

**Comment by JavacHolt** [comment]
Hi Robert, sorry to take so long, I've decided not to take this any
further, will try to wipe this, tho that may not work. But it may be good
for parts.
So thanks for your time, and at least I learnt something.

J

**Comment by remay** [comment]
Thanks for coming back.. Sorry that we couldn't get your Hudl going again.
