### ISSUE TITLE
Oops, I've bricked my Hudl 1!

### ISSUE THREAD

**Issue by tarmacalastair** [remay/tmf-hudl#31]
**NOW FIXED - see below and check your USB cable!**

Hello, I was really excited when I discovered your Github pages as my Hudl has been unused for ages and my elderly father wanted to try an ebook reader so I thought this would be ideal.

Anyway, I had prevously rooted the Hudl and had a different bootloader (CWM I think) so I couldn't get the SD image to work so I booted a laptop with your bootable USB. All appeared to go ok for a bit and then it stalled. I wiggled the USB cable and things moved along a bit more and kept stalling. After about 3 hours it appeared to complete but, when the instructions said the Hudl would reboot, nothing happened. It looks like something went horribly wrong due to a faulty cable. I have changed the cable and can now repeat the process with a new cable in about 4 minutes but still nothing appears on the screen of the Hudl.

When I connect the Hudl with the new USB lead to my Ubuntu laptop and issue _lsusb_, this is what I see:
`Bus 002 Device 003: ID 2207:310b Fuzhou Rockchip Electronics Company RK3188 in Mask ROM mode`

Just wondered if you've come across this before and have any bright ideas? It would be good to be able to use it if possible but it is pretty old so no problem if not.

(I've tried starting the Hudl with Vol+ and the power button, Vol- & power, a pin in the reset hole, holding the buttons for ages, etc and nothing seems to work)

Thanks for all your work.
Alastair

**Comment by tarmacalastair** [comment]
Managed to find a Windows laptop so I've tried the instructions at https://github.com/remay/tmf-hudl/wiki/Flashing-from-a-Windows-Computer-using-RK-Batch-Tool. Windows 10 makes a USB connect/disconnect sound when I press the reset button and the block appeared green to start with and then flashing yellow....but then it went red at the end. All appeared to complete successfully until the last line shown here:

> **********Restore Action**********
**********Restore Start Total<1>**********
<Layer 2-2> Test Device Start
<Layer 2-2> Test Device Success
<Layer 2-2> Lowerformat Device Start
<Layer 2-2> Lowerformat Device Success
<Layer 2-2> Test Device Start
<Layer 2-2> Test Device Success
<Layer 2-2> Check Chip Start
<Layer 2-2> Check Chip Success
<Layer 2-2> Get FlashInfo Start
<Layer 2-2> Get FlashInfo Success
<Layer 2-2> Prepare IDB Start
<Layer 2-2> Prepare IDB Success
<Layer 2-2> Download IDB Start
<Layer 2-2> Download IDB Fail
**********Restore Done Success<0> Fail<1> Time<159969>ms**********

Just in case this means anything to anyone. Thanks

**Comment by remay** [comment]
That suggests you don't have the drivers installed correctly.  In Mask ROM mode the square should go blue, if I remember correctly.    Did you do the registry edit in Step 1.3 of the instructions at https://github.com/remay/tmf-hudl/wiki/Flashing-from-a-Windows-Computer-using-RK-Batch-Tool ?

**Comment by remay** [comment]
I may be wrong about the blue colour - sorry its a long time since I got a device into that state.  Flashing over usb cable it's important that the USB cable is good and that you have a good connection.  Hudl's are notorious for the USB connectors to become deformed , the USB connector should be snug and not have much 'wobble'.   New connectors are available for £3ish from ebay and are quite easy to replace  if needed.

**Comment by tarmacalastair** [comment]
Wow, thanks for the feedback. I checked all the drivers and the reg key and then I dug out several USB leads from a drawer and tried a few until I had complete success with one of them. Interesting how many USB leads failed.

The RKbatchtool  process carried on much longer than before, the tablet rebooted (the previously black screen sprang to life) and all now appears to be working.

Brilliant, many thanks.

**Comment by remay** [comment]
Awesome result.   Glad it all worked out.
