### ISSUE TITLE
Issues Rebooting with USB on Toshiba Laptops

### ISSUE THREAD

**Issue by LukeDavis03** [remay/tmf-hudl#40]
Hello there!

the rockchip flash method didn't work for me as it said something about "download IDB fail", i did not have a SD card to hand so i made a USB stick using the image provided,

i first tried flashing using a Toshiba Satellite C660-2EL and a White USB cable, however when it got to the reboot state the device appeared totally hard bricked, until i removed the battery and restarted again , this time using a Toshiba Satellite Pro A300-22c the flash and reboot worked this time, with it formatting the partitions and it finally rebooting twice, however on the second reboot its just stuck on the "Powered By android Logo" i left it overnight and woke up to a dead battery, is there something else I should try
![20220522_090844](https://user-images.githubusercontent.com/106009950/169685593-b00a2013-9d11-427b-8503-09be54872439.jpg)
?

**Comment by remay** [comment]
Hi Luke - without access to your device it's really difficult to tell what's happened, but your symptoms are consistent with a failure to flash successfully.

In my experience flashing over USB is very sensitive to the quality of the USB cable, and your message 'download IDB fail" when first attempting the flash is, again, indicative of a problem with communications.    Further, once you have a PC booting from the USB stick method it really shouldn't fail if the cable is reliable, but it is always possible that one of the laptops has some incompatible hardware.   The USB stick flashing mechanism does not verify what it wrote to the Hudl.

If you have some other usb cables to try then please re-try with them - generally short, high quality, USB cables are needed for either of these methods to be reliable.

My recommendation is to use the SD card method - using this method it is also possible for me to make special builds that may identify problems if you still have them (for example I've come across a couple of Hudl's that appear to have got their flash chips into a read-only state and for which fashing can't be done successfully).

Let me know if I can be of further help.
Rob.

**Comment by LukeDavis03** [comment]
Hello Rob

Thanks for getting back to me.

The issues i have experienced  with flashing have been rectified, i located
a Unused SD card and flashed via that method, reviving both tablets.

The quality of the USB cable i used may be to blame, however both charging
ports in both Hudls seemed to look "very worn out" to add more.. A small
coil on one port is damaged which may explain why the blue tablet i have
didn't even connect to a PC but would charge,

I decided the SD method was my best bet and its a total success... Both
tablets are now fully functioning again!

**Comment by remay** [comment]
Awesome.   I've very likely that either the cable or ports are to blame for the problems you had originally.

Glad it's all working for you.
